In [2]:
# importing relevant packages
import pandas as pd
import numpy as np
pd.set_option('display.max_rows', 500)

In [4]:
df=pd.read_csv('Auto_Insurance_Claims_Sample (1).csv')
print(df.head())

  Customer Country State Code     State  Claim Amount Response  Coverage  \
0  BU79786      US         KS    Kansas    276.351928       No     Basic
1  QZ44356      US         NE  Nebraska    697.953590       No  Extended
2  AI49188      US         OK  Oklahoma   1288.743165       No   Premium
3  WW63253      US         MO  Missouri    764.586183       No     Basic
4  HB64268      US         KS    Kansas    281.369258       No     Basic

  Education Effective To Date EmploymentStatus     ...       \
0  Bachelor           2/24/11         Employed     ...
1  Bachelor           1/31/11       Unemployed     ...
2  Bachelor           2/19/11         Employed     ...
3  Bachelor           1/20/11       Unemployed     ...
4  Bachelor            2/3/11         Employed     ...

  Months Since Policy Inception  Number of Open Complaints Number of Policies  \
0                             5                          0                  1
1                            42                          0                  8
2                            38                          0                  2
3                            65                          0                  7
4                            44                          0                  1

      Policy Type        Policy  Claim Reason  Sales Channel  \
0  Corporate Auto  Corporate L3     Collision          Agent
1   Personal Auto   Personal L3  Scratch/Dent          Agent
2   Personal Auto   Personal L3     Collision          Agent
3  Corporate Auto  Corporate L2     Collision    Call Center
4   Personal Auto   Personal L1     Collision          Agent

   Total Claim Amount  Vehicle Class Vehicle Size
0          384.811147   Two-Door Car      Medsize
1         1131.464935  Four-Door Car      Medsize
2          566.472247   Two-Door Car      Medsize
3          529.881344            SUV      Medsize
4          138.130879  Four-Door Car      Medsize

[5 rows x 26 columns]

In [5]:
# exploring the data
print(df.shape)
print(df.columns)

(9134, 26)
Index(['Customer', 'Country', 'State Code', 'State', 'Claim Amount',
       'Response', 'Coverage', 'Education', 'Effective To Date',
       'EmploymentStatus', 'Gender', 'Income', 'Location Code',
       'Marital Status', 'Monthly Premium Auto', 'Months Since Last Claim',
       'Months Since Policy Inception', 'Number of Open Complaints',
       'Number of Policies', 'Policy Type', 'Policy', 'Claim Reason',
       'Sales Channel', 'Total Claim Amount', 'Vehicle Class', 'Vehicle Size'],
      dtype='object')

In [6]:
print(df.dtypes)
print(df.describe())

Customer                          object
Country                           object
State Code                        object
State                             object
Claim Amount                     float64
Response                          object
Coverage                          object
Education                         object
Effective To Date                 object
EmploymentStatus                  object
Gender                            object
Income                             int64
Location Code                     object
Marital Status                    object
Monthly Premium Auto               int64
Months Since Last Claim            int64
Months Since Policy Inception      int64
Number of Open Complaints          int64
Number of Policies                 int64
Policy Type                       object
Policy                            object
Claim Reason                      object
Sales Channel                     object
Total Claim Amount               float64
Vehicle Class                     object
Vehicle Size                      object
dtype: object
       Claim Amount        Income  Monthly Premium Auto  \
count   9134.000000   9134.000000           9134.000000
mean     800.494047  37657.380009             93.219291
std      687.096761  30379.904734             34.407967
min      189.800768      0.000000             61.000000
25%      399.425179      0.000000             68.000000
50%      578.018220  33889.500000             83.000000
75%      896.216704  62320.000000            109.000000
max     8332.538119  99981.000000            298.000000

       Months Since Last Claim  Months Since Policy Inception  \
count              9134.000000                    9134.000000
mean                 15.097000                      48.064594
std                  10.073257                      27.905991
min                   0.000000                       0.000000
25%                   6.000000                      24.000000
50%                  14.000000                      48.000000
75%                  23.000000                      71.000000
max                  35.000000                      99.000000

       Number of Open Complaints  Number of Policies  Total Claim Amount
count                9134.000000         9134.000000         9134.000000
mean                    0.384388            2.966170          434.088794
std                     0.910384            2.390182          290.500092
min                     0.000000            1.000000            0.099007
25%                     0.000000            1.000000          272.258244
50%                     0.000000            2.000000          383.945434
75%                     0.000000            4.000000          547.514839
max                     5.000000            9.000000         2893.239678

In [15]:
# Removing the unnecessary information columns
data=df.drop(columns=['Country'])
# print the new size of data
print(data.shape)

(9134, 25)

In [16]:
data.State.value_counts()

Missouri    3150
Iowa        2601
Nebraska    1703
Oklahoma     882
Kansas       798
Name: State, dtype: int64

In [18]:
# Checking the duplicated rows
data.duplicated().value_counts()

False    9134
dtype: int64

In [19]:
# Checking the missing values
data.isnull().sum()

Customer                         0
State Code                       0
State                            0
Claim Amount                     0
Response                         0
Coverage                         0
Education                        0
Effective To Date                0
EmploymentStatus                 0
Gender                           0
Income                           0
Location Code                    0
Marital Status                   0
Monthly Premium Auto             0
Months Since Last Claim          0
Months Since Policy Inception    0
Number of Open Complaints        0
Number of Policies               0
Policy Type                      0
Policy                           0
Claim Reason                     0
Sales Channel                    0
Total Claim Amount               0
Vehicle Class                    0
Vehicle Size                     0
dtype: int64

In [20]:
# Removing the white spaces in column names
data.columns = data.columns.str.replace(' ', '')
# print the columns names
print(data.columns)

Index(['Customer', 'StateCode', 'State', 'ClaimAmount', 'Response', 'Coverage',
       'Education', 'EffectiveToDate', 'EmploymentStatus', 'Gender', 'Income',
       'LocationCode', 'MaritalStatus', 'MonthlyPremiumAuto',
       'MonthsSinceLastClaim', 'MonthsSincePolicyInception',
       'NumberofOpenComplaints', 'NumberofPolicies', 'PolicyType', 'Policy',
       'ClaimReason', 'SalesChannel', 'TotalClaimAmount', 'VehicleClass',
       'VehicleSize'],
      dtype='object')

In [21]:
data.EffectiveToDate.str.replace('/', '-')

0       2-24-11
1       1-31-11
2       2-19-11
3       1-20-11
4        2-3-11
5       1-25-11
6       2-24-11
7       1-18-11
8       1-26-11
9       2-17-11
10      2-21-11
11       1-6-11
12       2-6-11
13      1-10-11
14      1-18-11
15      1-17-11
16       2-6-11
17       1-5-11
18      2-27-11
19      1-14-11
20      2-19-11
21      1-21-11
22      1-26-11
23      2-24-11
24       2-5-11
25      1-29-11
26      2-28-11
27      2-12-11
28       2-2-11
29       2-7-11
30      2-28-11
31      1-22-11
32      1-25-11
33      1-18-11
34      2-13-11
35      1-15-11
36       1-8-11
37       2-6-11
38      1-25-11
39       2-7-11
40      1-18-11
41      1-11-11
42      1-28-11
43       2-8-11
44      2-23-11
45      1-25-11
46      1-31-11
47       1-2-11
48       2-7-11
49      1-18-11
50      1-17-11
51      1-11-11
52      2-21-11
53      2-16-11
54      1-17-11
55       2-5-11
56      2-13-11
57      2-23-11
58      1-28-11
59      2-28-11
60       1-2-11
61      1-22-11
62      1-15-11
63      1-27-11
64      1-23-11
65      1-31-11
66      1-26-11
67      1-10-11
68      1-27-11
69       1-9-11
70      2-24-11
71      2-11-11
72      2-12-11
73       2-4-11
74      1-18-11
75      2-11-11
76       2-1-11
77      2-15-11
78       2-6-11
79      2-27-11
80      1-26-11
81      2-26-11
82      1-27-11
83      1-16-11
84      1-27-11
85      2-28-11
86      1-25-11
87       1-1-11
88       2-1-11
89      2-19-11
90      1-27-11
91      2-27-11
92      1-17-11
93      2-10-11
94      1-24-11
95      2-24-11
96      2-15-11
97      2-16-11
98      1-22-11
99      2-25-11
100     1-11-11
101     1-31-11
102     1-12-11
103     2-16-11
104      2-9-11
105     1-19-11
106      1-4-11
107      1-9-11
108     1-27-11
109     2-14-11
110     2-27-11
111     2-12-11
112     2-26-11
113     2-20-11
114      2-2-11
115     2-15-11
116     2-18-11
117     1-21-11
118     1-15-11
119      2-5-11
120     2-24-11
121      1-5-11
122     1-28-11
123     1-12-11
124     2-16-11
125      1-3-11
126      2-7-11
127     1-13-11
128      1-3-11
129     2-17-11
130     1-21-11
131     1-26-11
132     1-31-11
133      1-2-11
134      2-7-11
135     1-26-11
136     1-11-11
137     1-15-11
138      2-8-11
139     1-11-11
140      1-9-11
141      2-4-11
142     1-21-11
143     2-16-11
144     2-24-11
145     1-18-11
146     1-30-11
147      1-9-11
148      2-1-11
149     2-28-11
150     1-31-11
151     2-17-11
152     2-12-11
153     2-24-11
154      2-1-11
155      2-6-11
156     1-23-11
157     1-21-11
158     1-20-11
159      1-6-11
160     2-22-11
161     2-27-11
162     2-21-11
163     1-29-11
164     2-22-11
165     2-21-11
166     1-10-11
167     1-18-11
168     1-16-11
169      1-6-11
170     1-27-11
171     1-15-11
172      1-9-11
173     1-28-11
174     2-26-11
175      1-4-11
176      2-1-11
177     1-27-11
178     2-14-11
179     1-23-11
180     2-18-11
181     1-24-11
182     2-18-11
183     1-19-11
184      1-4-11
185      2-7-11
186     1-30-11
187     2-17-11
188     1-13-11
189      2-8-11
190     1-29-11
191      2-5-11
192     1-20-11
193     1-27-11
194      1-9-11
195     1-11-11
196     2-17-11
197     2-16-11
198     2-10-11
199     2-19-11
200     1-21-11
201     2-27-11
202      2-4-11
203     1-18-11
204      2-3-11
205      1-2-11
206      1-9-11
207     1-19-11
208     1-11-11
209     1-31-11
210     1-11-11
211     2-11-11
212     1-22-11
213     2-24-11
214     2-28-11
215     1-25-11
216     2-26-11
217     2-19-11
218      1-2-11
219      1-2-11
220     1-26-11
221      2-2-11
222     2-27-11
223     1-20-11
224     1-17-11
225     1-17-11
226     2-24-11
227     2-14-11
228     2-20-11
229     2-19-11
230      2-8-11
231      2-6-11
232     2-27-11
233      2-1-11
234     2-23-11
235     1-11-11
236     2-10-11
237     2-25-11
238     2-16-11
239     1-30-11
240     2-11-11
241     1-14-11
242     2-14-11
243      2-3-11
244     1-31-11
245     2-15-11
246     2-27-11
247     1-21-11
248     1-14-11
249     1-25-11
         ...
8884    2-26-11
8885    2-19-11
8886     2-9-11
8887    2-11-11
8888     1-7-11
8889     2-5-11
8890     2-3-11
8891    1-28-11
8892     2-2-11
8893    2-15-11
8894    1-23-11
8895    1-21-11
8896    1-30-11
8897    2-21-11
8898    1-18-11
8899    2-10-11
8900    2-18-11
8901    2-12-11
8902    2-20-11
8903     1-6-11
8904    2-10-11
8905    2-16-11
8906     1-9-11
8907    1-28-11
8908     1-2-11
8909     1-9-11
8910    1-28-11
8911    1-15-11
8912    2-10-11
8913    1-20-11
8914     2-1-11
8915     2-9-11
8916     2-8-11
8917    1-31-11
8918    2-10-11
8919    1-12-11
8920    2-22-11
8921    1-27-11
8922    2-26-11
8923     1-3-11
8924    1-24-11
8925     1-9-11
8926    2-14-11
8927     1-3-11
8928    2-19-11
8929    1-27-11
8930     2-9-11
8931    2-14-11
8932    2-14-11
8933    1-11-11
8934     1-2-11
8935     1-4-11
8936    1-21-11
8937    1-12-11
8938     2-1-11
8939     2-2-11
8940    1-11-11
8941     2-6-11
8942    1-10-11
8943     2-8-11
8944    1-28-11
8945    2-22-11
8946    1-26-11
8947     1-6-11
8948    2-14-11
8949    2-16-11
8950    2-12-11
8951     1-3-11
8952    1-11-11
8953    1-28-11
8954     2-3-11
8955    2-16-11
8956    1-27-11
8957    2-15-11
8958    1-28-11
8959     2-3-11
8960     1-2-11
8961     1-2-11
8962     2-9-11
8963    2-11-11
8964    1-15-11
8965    1-26-11
8966     1-5-11
8967    1-26-11
8968    2-13-11
8969    1-17-11
8970    2-26-11
8971     2-5-11
8972    2-24-11
8973     2-7-11
8974    2-26-11
8975    1-21-11
8976    2-16-11
8977    2-18-11
8978    1-11-11
8979    1-18-11
8980     1-5-11
8981     2-9-11
8982    1-17-11
8983     1-7-11
8984     1-9-11
8985     1-6-11
8986    1-12-11
8987    1-10-11
8988    1-28-11
8989    1-25-11
8990    1-24-11
8991    1-30-11
8992    1-10-11
8993    2-27-11
8994    2-26-11
8995     2-1-11
8996    1-20-11
8997    1-20-11
8998    2-24-11
8999    1-19-11
9000    2-17-11
9001    1-18-11
9002    1-23-11
9003    2-25-11
9004    1-27-11
9005     2-4-11
9006    2-23-11
9007    1-16-11
9008    1-17-11
9009    1-25-11
9010    1-27-11
9011     1-9-11
9012    2-14-11
9013     2-6-11
9014    1-30-11
9015    1-30-11
9016     2-7-11
9017     2-7-11
9018    1-15-11
9019    1-25-11
9020    2-12-11
9021    2-16-11
9022     2-3-11
9023    2-16-11
9024    1-29-11
9025     1-9-11
9026    2-22-11
9027    2-27-11
9028    2-11-11
9029    2-25-11
9030     2-6-11
9031     1-8-11
9032     2-2-11
9033    2-20-11
9034    1-22-11
9035    2-25-11
9036    1-26-11
9037    2-22-11
9038    1-16-11
9039    2-18-11
9040     2-5-11
9041     1-2-11
9042    1-20-11
9043    2-23-11
9044    2-18-11
9045    1-31-11
9046     2-6-11
9047     1-8-11
9048     2-8-11
9049    2-16-11
9050    2-17-11
9051    2-24-11
9052    2-14-11
9053    2-13-11
9054    1-24-11
9055    1-15-11
9056    2-19-11
9057    1-22-11
9058    2-11-11
9059     2-8-11
9060     1-3-11
9061    1-28-11
9062    2-17-11
9063     1-1-11
9064     2-9-11
9065    1-11-11
9066    2-20-11
9067     2-4-11
9068     2-4-11
9069    2-12-11
9070    1-26-11
9071    2-17-11
9072    2-23-11
9073     2-2-11
9074    2-19-11
9075     2-1-11
9076    1-11-11
9077    1-20-11
9078     2-4-11
9079    2-25-11
9080    2-11-11
9081     1-6-11
9082     2-2-11
9083     2-5-11
9084    2-10-11
9085     1-1-11
9086    2-20-11
9087    1-24-11
9088    2-28-11
9089    1-13-11
9090     1-7-11
9091     1-2-11
9092    2-14-11
9093    1-26-11
9094    2-14-11
9095     2-9-11
9096    1-30-11
9097    2-11-11
9098    1-29-11
9099    2-10-11
9100    1-16-11
9101    1-26-11
9102     2-5-11
9103     1-1-11
9104     1-9-11
9105    2-22-11
9106    1-12-11
9107    1-26-11
9108    1-28-11
9109    1-25-11
9110    1-14-11
9111     2-7-11
9112    2-12-11
9113     1-6-11
9114    2-23-11
9115    2-17-11
9116    1-26-11
9117    1-20-11
9118    2-10-11
9119    1-13-11
9120    2-19-11
9121    1-17-11
9122     2-1-11
9123    1-19-11
9124    1-20-11
9125    1-31-11
9126     1-9-11
9127    2-12-11
9128     1-6-11
9129    2-10-11
9130    2-12-11
9131     2-6-11
9132     2-3-11
9133    2-14-11
Name: EffectiveToDate, Length: 9134, dtype: object

In [22]:
# Changing data type
data['EffectiveToDate'] = pd.to_datetime(data['EffectiveToDate'], errors='coerce')

In [23]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9134 entries, 0 to 9133
Data columns (total 25 columns):
Customer                      9134 non-null object
StateCode                     9134 non-null object
State                         9134 non-null object
ClaimAmount                   9134 non-null float64
Response                      9134 non-null object
Coverage                      9134 non-null object
Education                     9134 non-null object
EffectiveToDate               9134 non-null datetime64[ns]
EmploymentStatus              9134 non-null object
Gender                        9134 non-null object
Income                        9134 non-null int64
LocationCode                  9134 non-null object
MaritalStatus                 9134 non-null object
MonthlyPremiumAuto            9134 non-null int64
MonthsSinceLastClaim          9134 non-null int64
MonthsSincePolicyInception    9134 non-null int64
NumberofOpenComplaints        9134 non-null int64
NumberofPolicies              9134 non-null int64
PolicyType                    9134 non-null object
Policy                        9134 non-null object
ClaimReason                   9134 non-null object
SalesChannel                  9134 non-null object
TotalClaimAmount              9134 non-null float64
VehicleClass                  9134 non-null object
VehicleSize                   9134 non-null object
dtypes: datetime64[ns](1), float64(2), int64(6), object(16)
memory usage: 1.7+ MB

In [37]:
# exporting data
data.to_csv('Auto_Insurance_Dataset.csv', index = False)